#!/usr/bin/python3
def raise_exception():
    x = "5"
    y = "3"
    result = x / y
